#!/usr/bin/env python3
"""Materialize a conservative correctness fix for quiet-check pruning.

The promoted v3.26 quiet-SEE gate exempts direct checks only. A quiet move can
also give a discovered rook/bishop/queen check by vacating its origin square.
Such a move must not be discarded by quiet SEE before board_make(). Castling is
also generated by board_gen_quiets(), but is not an ordinary quiet for the
surrounding LMP/history logic, so exempt it from this SEE gate as well.
"""
from __future__ import annotations

import argparse
from pathlib import Path

SOURCE = Path("engine/c/zchezz_v326/search.c")

OLD_HELPER = r'''/* Cheap direct-check test ported from v4.02.  It intentionally detects
 * direct checks only; discovered checks remain outside this cheap prune gate. */
static inline int quiet_direct_check(const Board *bd, int from, int to) {
    int ksq = bd->turn == COL_W ? bd->bk : bd->wk;
    uint64_t occ = bd->occ & ~((uint64_t)1 << from);
    switch (PC_TYPE(bd->b[from])) {
        case 1: return (bd->turn == COL_W ? wpawn_attacks_bb((uint64_t)1 << to)
                                          : bpawn_attacks_bb((uint64_t)1 << to)) >> ksq & 1;
        case 2: return (NATK[to] >> ksq) & 1;
        case 3: return (bish_attacks(to, occ) >> ksq) & 1;
        case 4: case 5:
            return ((rook_attacks(to, occ) | bish_attacks(to, occ)) >> ksq) & 1;
        default: return 0;
    }
}
'''

NEW_HELPER = r'''/* Exact pre-move check guard for ordinary non-capturing moves.
 * Besides direct checks, detect discovered slider checks created by vacating
 * the from-square.  This remains much cheaper than make/unmake + board_in_check
 * and is used only to keep checking moves out of quiet SEE pruning. */
static inline int quiet_gives_check(const Board *bd, int from, int to) {
    int ksq = bd->turn == COL_W ? bd->bk : bd->wk;
    uint64_t from_bb = (uint64_t)1 << from;
    uint64_t to_bb   = (uint64_t)1 << to;
    uint64_t occ_after = (bd->occ & ~from_bb) | to_bb;
    int direct = 0;
    switch (PC_TYPE(bd->b[from])) {
        case 1:
            direct = (int)(((bd->turn == COL_W ? wpawn_attacks_bb(to_bb)
                                                  : bpawn_attacks_bb(to_bb)) >> ksq) & 1);
            break;
        case 2:
            direct = (int)((NATK[to] >> ksq) & 1);
            break;
        case 3:
            direct = (int)((bish_attacks(to, occ_after) >> ksq) & 1);
            break;
        case 4:
            direct = (int)((rook_attacks(to, occ_after) >> ksq) & 1);
            break;
        case 5:
            direct = (int)(((rook_attacks(to, occ_after) |
                              bish_attacks(to, occ_after)) >> ksq) & 1);
            break;
        default:
            break;
    }
    if (direct) return 1;

    /* The moving piece still exists in bd->bb[] at `from`; remove that bit
     * when asking whether another friendly slider attacks the enemy king in
     * the post-move occupancy.  The moved slider's direct check was handled
     * above from its destination square. */
    int base = bd->turn == COL_W ? 0 : 6;
    uint64_t rq = (bd->bb[base + 3] | bd->bb[base + 4]) & ~from_bb;
    uint64_t bq = (bd->bb[base + 2] | bd->bb[base + 4]) & ~from_bb;
    if (rook_attacks(ksq, occ_after) & rq) return 1;
    if (bish_attacks(ksq, occ_after) & bq) return 1;
    return 0;
}
'''

OLD_GATE = r'''                if (!in_check && !is_pv && legal_count > 0 && depth <= 4 &&
                    !is_killer &&
                    !(cur_prev_ft >= 0 && ss->counter_move[cur_prev_ft] == (mfr*64+mto)) &&
                    !quiet_direct_check(b, mfr, mto)) {
'''

NEW_GATE = r'''                if (!in_check && !is_pv && is_quiet && legal_count > 0 && depth <= 4 &&
                    !is_killer &&
                    !(cur_prev_ft >= 0 && ss->counter_move[cur_prev_ft] == (mfr*64+mto)) &&
                    !quiet_gives_check(b, mfr, mto)) {
'''


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"expected one {label}, found {count}")
    return text.replace(old, new, 1)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", type=Path, default=SOURCE)
    args = ap.parse_args()

    text = args.source.read_text(encoding="utf-8")
    text = replace_once(text, OLD_HELPER, NEW_HELPER, "quiet check helper")
    text = replace_once(text, OLD_GATE, NEW_GATE, "quiet SEE gate")
    args.source.write_text(text, encoding="utf-8")
    print(f"Applied quiet discovered-check guard to {args.source}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
