#!/usr/bin/env python3
"""Instrument v3.25 search in-place for structural diagnostics or TT experiments.

The committed engine source remains untouched on main. This helper is intended for
CI/worktree experiments: it rewrites search.c deterministically and fails loudly if
the expected v3.25 source patterns drift.

It works with no command-line arguments. Defaults are configured below; CLI flags
only override them.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re

SOURCE = Path("engine/c/zchezz_v325/search.c")
ENABLE_DIAGNOSTICS = True
STALE_GENERATION_IS_MISS = False


DIAG_BLOCK = r'''

/* SEARCH_DIAGNOSTICS: generated by tests/instrument_v325_search.py.
 * Diagnostic-only counters. They intentionally do not participate in search
 * decisions and are never committed into the production engine source. */
typedef struct {
    unsigned long long ab_nodes;
    unsigned long long q_nodes;
    unsigned long long beta_cutoffs;
    unsigned long long cutoff_rank_1;
    unsigned long long cutoff_rank_2;
    unsigned long long cutoff_rank_3;
    unsigned long long cutoff_rank_4_7;
    unsigned long long cutoff_rank_8p;
    unsigned long long tt_move_cutoffs;
    unsigned long long stale_tt_move_cutoffs;
    unsigned long long capture_cutoffs;
    unsigned long long quiet_cutoffs;
    unsigned long long tt_current_hits;
    unsigned long long tt_stale_hits;
    unsigned long long tt_score_cutoffs;
    unsigned long long pvs_zero_windows;
    unsigned long long pvs_researches;
    unsigned long long lmr_applied;
    unsigned long long lmr_researches;
    unsigned long long lmr_reduction_sum;
    unsigned long long lmr_r1;
    unsigned long long lmr_r2;
    unsigned long long lmr_r3p;
} SearchDiag;

static SearchDiag g_diag;

static int diag_same_move(const Move *a, const Move *b) {
    return a && b && (a->from || a->to) &&
           a->from == b->from && a->to == b->to &&
           a->prom == b->prom && a->epc == b->epc && a->castle == b->castle;
}

static void diag_lmr(int reduction) {
    if (reduction <= 0) return;
    g_diag.lmr_applied++;
    g_diag.lmr_reduction_sum += (unsigned)reduction;
    if (reduction == 1) g_diag.lmr_r1++;
    else if (reduction == 2) g_diag.lmr_r2++;
    else g_diag.lmr_r3p++;
}

static void diag_cutoff(int rank, const Move *best, const Move *tt_move,
                        int tte_hit, const Board *b) {
    g_diag.beta_cutoffs++;
    if (rank <= 1) g_diag.cutoff_rank_1++;
    else if (rank == 2) g_diag.cutoff_rank_2++;
    else if (rank == 3) g_diag.cutoff_rank_3++;
    else if (rank <= 7) g_diag.cutoff_rank_4_7++;
    else g_diag.cutoff_rank_8p++;

    if (tte_hit && diag_same_move(best, tt_move)) {
        g_diag.tt_move_cutoffs++;
        if (tte_hit == 2) g_diag.stale_tt_move_cutoffs++;
    }

    if (best && b && (best->from || best->to)) {
        if (best->epc || b->b[best->to]) g_diag.capture_cutoffs++;
        else g_diag.quiet_cutoffs++;
    }
}

static void diag_report(void) {
    fprintf(stderr,
        "[SEARCH_DIAG] ab_nodes=%llu q_nodes=%llu beta_cutoffs=%llu "
        "cutoff_rank_1=%llu cutoff_rank_2=%llu cutoff_rank_3=%llu "
        "cutoff_rank_4_7=%llu cutoff_rank_8p=%llu "
        "tt_move_cutoffs=%llu stale_tt_move_cutoffs=%llu "
        "capture_cutoffs=%llu quiet_cutoffs=%llu "
        "tt_current_hits=%llu tt_stale_hits=%llu tt_score_cutoffs=%llu "
        "pvs_zero_windows=%llu pvs_researches=%llu "
        "lmr_applied=%llu lmr_researches=%llu lmr_reduction_sum=%llu "
        "lmr_r1=%llu lmr_r2=%llu lmr_r3p=%llu\n",
        g_diag.ab_nodes, g_diag.q_nodes, g_diag.beta_cutoffs,
        g_diag.cutoff_rank_1, g_diag.cutoff_rank_2, g_diag.cutoff_rank_3,
        g_diag.cutoff_rank_4_7, g_diag.cutoff_rank_8p,
        g_diag.tt_move_cutoffs, g_diag.stale_tt_move_cutoffs,
        g_diag.capture_cutoffs, g_diag.quiet_cutoffs,
        g_diag.tt_current_hits, g_diag.tt_stale_hits, g_diag.tt_score_cutoffs,
        g_diag.pvs_zero_windows, g_diag.pvs_researches,
        g_diag.lmr_applied, g_diag.lmr_researches, g_diag.lmr_reduction_sum,
        g_diag.lmr_r1, g_diag.lmr_r2, g_diag.lmr_r3p);
}

#if defined(__GNUC__) || defined(__clang__)
__attribute__((constructor))
#endif
static void diag_register(void) { atexit(diag_report); }
'''


def replace_exact(text: str, old: str, new: str, *, count: int | None = None, label: str) -> str:
    found = text.count(old)
    if count is not None and found != count:
        raise RuntimeError(f"{label}: expected {count} matches, found {found}")
    if found == 0:
        raise RuntimeError(f"{label}: source pattern not found")
    return text.replace(old, new)


def apply_diagnostics(text: str) -> str:
    text = replace_exact(
        text,
        '#include <time.h>\n',
        '#include <time.h>\n' + DIAG_BLOCK,
        count=1,
        label="diagnostic declarations",
    )

    q_anchor = """static int qsearch(SearchState *ss, Board *b, int alpha, int beta, int ply) {
    if (ply >= MAX_PLY-1) return eval_stm(b);
    if (ss->nodes_total >= ss->node_limit || time_up(ss)) return eval_stm(b);
    ss->nodes++; ss->nodes_total++;
"""
    text = replace_exact(
        text,
        q_anchor,
        q_anchor + "    g_diag.q_nodes++;\n",
        count=1,
        label="qsearch node counter",
    )

    # The remaining identical node-accounting statement belongs to alpha_beta.
    node_stmt = "    ss->nodes++; ss->nodes_total++;\n"
    if text.count(node_stmt) != 1:
        raise RuntimeError(f"alpha-beta node counter: expected 1 remaining match, found {text.count(node_stmt)}")
    text = text.replace(node_stmt, node_stmt + "    g_diag.ab_nodes++;\n", 1)

    # Count TT generation quality at the probe itself so qsearch and main search
    # are both represented.
    stale_block = """        if (tt_age(e, gen) != 0) {
            out->score = TT_EVAL_NONE;
            out->depth = 0;
            out->flag = TT_UPPER;
            out->static_eval = TT_EVAL_NONE;
            return 2;
        }
"""
    stale_diag = """        if (tt_age(e, gen) != 0) {
            g_diag.tt_stale_hits++;
            out->score = TT_EVAL_NONE;
            out->depth = 0;
            out->flag = TT_UPPER;
            out->static_eval = TT_EVAL_NONE;
            return 2;
        }
        g_diag.tt_current_hits++;
"""
    text = replace_exact(text, stale_block, stale_diag, count=1, label="TT generation counters")

    tt_cut = """            if (tte.flag == TT_EXACT) return tte.score;
            if (tte.flag == TT_LOWER && tte.score >= beta) return tte.score;
            if (tte.flag == TT_UPPER && tte.score <= alpha) return tte.score;
"""
    tt_cut_diag = """            if (tte.flag == TT_EXACT) { g_diag.tt_score_cutoffs++; return tte.score; }
            if (tte.flag == TT_LOWER && tte.score >= beta) { g_diag.tt_score_cutoffs++; return tte.score; }
            if (tte.flag == TT_UPPER && tte.score <= alpha) { g_diag.tt_score_cutoffs++; return tte.score; }
"""
    text = replace_exact(text, tt_cut, tt_cut_diag, count=1, label="main TT score cutoffs")

    cutoff = "            if (alpha >= beta) goto cutoff;\n"
    cutoff_diag = (
        "            if (alpha >= beta) {\n"
        "                diag_cutoff(legal_count, &best_move, &pv_move, tte_hit, b);\n"
        "                goto cutoff;\n"
        "            }\n"
    )
    text = replace_exact(text, cutoff, cutoff_diag, count=3, label="beta cutoff rank sites")

    # Stage 1 TT/PV move has deeper indentation than the generated-move stages.
    cutoff_tt = "                    if (alpha >= beta) goto cutoff;\n"
    cutoff_tt_diag = (
        "                    if (alpha >= beta) {\n"
        "                        diag_cutoff(legal_count, &best_move, &pv_move, tte_hit, b);\n"
        "                        goto cutoff;\n"
        "                    }\n"
    )
    text = replace_exact(text, cutoff_tt, cutoff_tt_diag, count=1, label="TT-stage beta cutoff site")

    zw_call = "sc = -alpha_beta(ss, b, depth-1-reduce+check_ext, -alpha-1, -alpha, null_pv, &null_len, ply+1, gives_check);"
    text = replace_exact(
        text,
        zw_call,
        "diag_lmr(reduce); g_diag.pvs_zero_windows++;\n                " + zw_call,
        count=3,
        label="LMR/PVS zero-window sites",
    )

    text = replace_exact(
        text,
        "if (sc > alpha && reduce > 0) {\n",
        "if (sc > alpha && reduce > 0) {\n                    g_diag.lmr_researches++;\n",
        count=2,
        label="braced LMR re-search sites",
    )
    text = replace_exact(
        text,
        "if (sc > alpha && reduce > 0)\n                    sc = -alpha_beta",
        "if (sc > alpha && reduce > 0) {\n                    g_diag.lmr_researches++;\n                    sc = -alpha_beta",
        count=1,
        label="unbraced LMR re-search site",
    )
    # Close the block introduced above at the unique losing-capture form.
    text = replace_exact(
        text,
        "ply+1, gives_check);\n                if (sc > alpha && sc < beta)\n",
        "ply+1, gives_check);\n                }\n                if (sc > alpha && sc < beta)\n",
        count=1,
        label="unbraced LMR re-search closure",
    )

    text = replace_exact(
        text,
        "if (sc > alpha && sc < beta) {\n",
        "if (sc > alpha && sc < beta) {\n                    g_diag.pvs_researches++;\n",
        count=2,
        label="braced PVS re-search sites",
    )
    text = replace_exact(
        text,
        "if (sc > alpha && sc < beta)\n                    sc = -alpha_beta",
        "if (sc > alpha && sc < beta) {\n                    g_diag.pvs_researches++;\n                    sc = -alpha_beta",
        count=1,
        label="unbraced PVS re-search site",
    )
    text = replace_exact(
        text,
        "ply+1, gives_check);\n            }\n            board_unmake(b);",
        "ply+1, gives_check);\n                }\n            }\n            board_unmake(b);",
        count=1,
        label="unbraced PVS re-search closure",
    )
    return text


def apply_stale_miss(text: str) -> str:
    stale_block = """        if (tt_age(e, gen) != 0) {
            out->score = TT_EVAL_NONE;
            out->depth = 0;
            out->flag = TT_UPPER;
            out->static_eval = TT_EVAL_NONE;
            return 2;
        }
"""
    return replace_exact(
        text,
        stale_block,
        "        if (tt_age(e, gen) != 0) continue;\n",
        count=1,
        label="stale-generation miss experiment",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--diagnostics", action=argparse.BooleanOptionalAction, default=ENABLE_DIAGNOSTICS)
    parser.add_argument("--stale-miss", action=argparse.BooleanOptionalAction, default=STALE_GENERATION_IS_MISS)
    args = parser.parse_args()

    text = args.source.read_text(encoding="utf-8")
    original = text
    if args.diagnostics:
        text = apply_diagnostics(text)
    if args.stale_miss:
        text = apply_stale_miss(text)
    if text == original:
        raise RuntimeError("no transformation requested")
    args.source.write_text(text, encoding="utf-8")
    print(f"instrumented {args.source}: diagnostics={args.diagnostics} stale_miss={args.stale_miss}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
