/* tools/opening_pool.h — shared opening-book plumbing for arena.c and
 * selfplay.c (engine/c/tools/, tracks the CURRENT engine API only, see
 * README.md in this directory).
 *
 * Factored out of arena.c (which had san_resolve()/move_to_san() as
 * static functions used only for its own PGN-opening-replay and --pgn
 * output) when selfplay.c needed the SAME SAN<->Move machinery for its
 * own opening-book support and its own --pgn output (rule 9 of
 * CLAUDE.md: a native tool must not lose the non-native path's
 * capabilities, and here specifically must not grow a SECOND,
 * independently-buggy SAN parser next to arena's working one).
 *
 * OpeningIndex (byte-offset opening corpus index) also lives here: it
 * is the C analogue of tests/run_selfplay.py's OpeningIndex class —
 * scans .pgn/.epd files ONCE at startup recording only (file, byte
 * offset, kind) triples, never loading the corpus text into memory, so
 * a 850k+ position / 100MB+ corpus is handled the same way the Python
 * harness handles it. Only selfplay.c uses this today (arena.c's own
 * OpeningPool fully materializes FENs, which is fine at arena's much
 * smaller opening-file scale — see arena.c's header comment on
 * OPENINGS); it lives in this shared file anyway because it is generic
 * (an EPD/PGN corpus indexer has no reason to be selfplay-specific) and
 * a future native tool wanting the same memory-efficient indexing
 * should not have to duplicate it out of selfplay.c.
 */
#ifndef ZCHEZZ_TOOLS_OPENING_POOL_H
#define ZCHEZZ_TOOLS_OPENING_POOL_H

#include <stddef.h>
#include <stdint.h>
#include "board.h"

/* ── SAN <-> Move (moved verbatim from arena.c) ─────────────────────── */

/* Given a legal-move list already generated by board_gen_moves() for the
 * CURRENT position `b`, find the one move that matches SAN token
 * `san_in` (move-number prefixes must already be stripped by the
 * caller; trailing +/#/!/? annotations are stripped here). NOT a
 * general PGN validator — trusts the input is well-formed mainline SAN
 * with no comments/variations/NAGs. Returns 1 and fills *out on
 * success, 0 on any parse/ambiguity failure (caller should stop
 * replaying that opening rather than guess). */
int san_resolve(const Board *b, const char *san_in, Move *out);

/* SAN move text for `m`, played from position `b` (BEFORE the move —
 * disambiguation needs the other legal moves of the same piece type at
 * THIS position). Does NOT append a check/mate suffix — the caller
 * appends '+'/'#' itself after board_make(), since that requires the
 * POST-move position. */
void move_to_san(const Board *b, const Move *m, char *out, size_t cap);

/* ── Recursive file-tree walk (openings/ is split into lines/*.pgn and
 * positions/*.epd subfolders — a flat, single-directory listing would
 * silently find nothing) ─────────────────────────────────────────── */

/* Calls cb(path, userdata) for every regular file under `root` whose
 * name ends in ".pgn" or ".epd" (case-insensitive), recursing into
 * subdirectories. If `root` itself names a file (not a directory), and
 * it has one of those two extensions, calls cb exactly once with it
 * regardless of extension case rules on the leaf argument (an explicit
 * single-file request is trusted). Returns the number of files visited,
 * or -1 if `root` does not exist at all. */
typedef void (*OpeningFileCB)(const char *path, void *userdata);
int opening_walk_files(const char *root, OpeningFileCB cb, void *userdata);

/* ── Byte-offset opening corpus index (selfplay.c) ──────────────────── */

typedef enum { OPEN_KIND_EPD = 0, OPEN_KIND_PGN = 1 } OpeningKind;

typedef struct {
    int      file_id;   /* index into OpeningIndex.files[] */
    uint64_t offset;     /* byte offset into that file */
    uint8_t  kind;        /* OpeningKind */
} OpeningEntry;

typedef struct {
    char        **files;       /* owned strings, one per indexed file */
    int           n_files, cap_files;
    OpeningEntry *entries;      /* owned, growable */
    size_t        n_entries, cap_entries;
} OpeningIndex;

/* One resolved opening: EITHER a custom start FEN (EPD entries, no
 * forced moves — search plays from ply 0 of that position) OR a forced
 * move sequence to replay from the standard start position (PGN
 * entries, replayed via board_make by the caller — see selfplay.c's
 * play_one_game()). Never both. */
#define OPENING_MAX_FORCED_MOVES 64
typedef struct {
    int   has_fen;
    char  fen[128];
    int   n_moves;
    Move  moves[OPENING_MAX_FORCED_MOVES];
} OpeningPick;

/* Build an index from every .pgn/.epd file found under `root`
 * (recursively — see opening_walk_files()). EPD files are cached to
 * "<path>.idx" (raw uint64 byte-offset array, native-endian — the same
 * format tests/run_selfplay.py's OpeningIndex._build_epd() writes via
 * struct.pack("<NQ"), so a cache built by either tool is reusable by
 * the other on a little-endian machine) so repeated indexing of a
 * 100MB+ EPD file only costs one fread() after the first run. Returns
 * 0 on success (even if zero files were found — check idx->n_entries),
 * -1 if `root` does not exist. */
int opening_index_build(OpeningIndex *idx, const char *root);
void opening_index_free(OpeningIndex *idx);

/* Resolve entry `i` into `out`. `scratch` is a throwaway Board this
 * call may freely overwrite (its own undo/nnue must already be bound by
 * the caller, e.g. worker_reset_board()-style) — used only to replay
 * PGN SAN moves via san_resolve()/board_make() to build out->moves[].
 * Returns 1 on success, 0 if the entry could not be parsed (caller
 * should skip / fall back). */
int opening_index_fetch(const OpeningIndex *idx, size_t i, Board *scratch, OpeningPick *out);

#endif /* ZCHEZZ_TOOLS_OPENING_POOL_H */
